backend:
  name: git-gateway
  branch: master

site_url: "https://muminhabeeb.info"
logo_url: "/favicon.svg"
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    label_singular: "Post"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    sort: "date:desc"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string, hint: "URL path. Keep it lowercase-with-dashes." }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: excerpt, label: Excerpt, widget: text, required: false, hint: "Short summary for listings and SEO (160 chars)." }
      - { name: body, label: Body, widget: markdown }

editor:
  preview: false

slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"

local_backend: true
