// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/mongo.ts
import { MongoClient } from "npm:mongodb@^7.5.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
var cached = null;
function db() {
  if (cached) return cached;
  const uri = runtimeEnv("MONGODB_URI")?.trim();
  if (!uri) throw new Error("MONGODB_URI is not configured for this server");
  cached = (async () => {
    const client = new MongoClient(uri, { maxPoolSize: 5 });
    await client.connect();
    return client.db();
  })().catch((err) => {
    cached = null;
    throw err;
  });
  return cached;
}
function serialize(doc) {
  const { _id, __v, ...rest } = doc;
  return { id: _id ? String(_id) : void 0, ...rest };
}
function textResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List Mumin Habeeb's published portfolio projects, newest or display-order first. Optionally filter to featured projects or a category.",
  inputSchema: {
    featured: z.boolean().optional().describe("Only return featured projects."),
    category: z.string().optional().describe("Filter by project category."),
    limit: z.number().int().min(1).max(50).optional().describe("Max projects to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ featured, category, limit }) => {
    const filter = { published: { $ne: false } };
    if (featured) filter.featured = true;
    if (category) filter.category = category;
    const docs = await (await db()).collection("projects").find(filter).sort({ display_order: 1, created_at: -1 }).limit(limit ?? 20).toArray();
    return textResult({ projects: docs.map(serialize) });
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch one published portfolio project in full detail (description, technologies, features, links) by its slug or title.",
  inputSchema: {
    slug: z2.string().trim().min(1).optional().describe("The project slug."),
    title: z2.string().trim().min(1).optional().describe("The project title, matched case-insensitively.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, title }) => {
    if (!slug && !title) throw new ToolError("Provide either a slug or a title.");
    const filter = { published: { $ne: false } };
    if (slug) filter.slug = slug;
    else filter.title = { $regex: `^${title.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, $options: "i" };
    const doc = await (await db()).collection("projects").findOne(filter);
    if (!doc) throw new ToolError("No published project matched that slug or title.");
    return textResult({ project: serialize(doc) });
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool3({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts with their titles, slugs, excerpts and tags. Use get_blog_post to read the full body of one post.",
  inputSchema: {
    tag: z3.string().optional().describe("Only return posts carrying this tag."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tag, limit }) => {
    const filter = { published: true };
    if (tag) filter.tags = tag;
    const docs = await (await db()).collection("blogposts").find(filter, { projection: { content: 0 } }).sort({ created_at: -1 }).limit(limit ?? 20).toArray();
    return textResult({ posts: docs.map(serialize) });
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool4, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var get_blog_post_default = defineTool4({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Read one published blog post in full, including its body content, by slug.",
  inputSchema: {
    slug: z4.string().trim().min(1).describe("The blog post slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const doc = await (await db()).collection("blogposts").findOne({ slug, published: true });
    if (!doc) throw new ToolError2("No published blog post matched that slug.");
    return textResult({ post: serialize(doc) });
  }
});

// src/lib/mcp/tools/list-achievements.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^4.4.3";
var list_achievements_default = defineTool5({
  name: "list_achievements",
  title: "List achievements",
  description: "List Mumin Habeeb's achievements, certifications and awards. Optionally filter to featured entries, a category, or a type such as 'certificate'.",
  inputSchema: {
    featured: z5.boolean().optional().describe("Only return featured achievements."),
    category: z5.string().optional().describe("Filter by achievement category."),
    type: z5.string().optional().describe("Filter by achievement type, e.g. 'certificate'."),
    limit: z5.number().int().min(1).max(100).optional().describe("Max entries to return (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ featured, category, type, limit }) => {
    const filter = {};
    if (featured) filter.featured = true;
    if (category) filter.category = category;
    if (type) filter.type = type;
    const docs = await (await db()).collection("achievements").find(filter).sort({ display_order: 1, created_at: -1 }).limit(limit ?? 30).toArray();
    return textResult({ achievements: docs.map(serialize) });
  }
});

// src/lib/mcp/tools/list-social-posts.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^4.4.3";
var list_social_posts_default = defineTool6({
  name: "list_social_posts",
  title: "List social posts",
  description: "List published social media posts shown on the site, optionally filtered to a single platform.",
  inputSchema: {
    platform: z6.string().optional().describe("Filter by platform, e.g. 'linkedin', 'github', 'x'."),
    limit: z6.number().int().min(1).max(50).optional().describe("Max posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ platform, limit }) => {
    const filter = { published: true };
    if (platform) filter.platform = { $regex: `^${platform}$`, $options: "i" };
    const docs = await (await db()).collection("socialmedias").find(filter).sort({ created_at: -1 }).limit(limit ?? 20).toArray();
    return textResult({ posts: docs.map(serialize) });
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "mumin-hacker-hub",
  title: "mumin-hacker-hub",
  version: "0.1.0",
  instructions: "Read-only access to Mumin Habeeb's portfolio site. Use `list_projects` and `get_project` for cybersecurity and development projects, `list_blog_posts` and `get_blog_post` for writing, `list_achievements` for certifications and awards, and `list_social_posts` for social activity. Only published, publicly visible content is exposed.",
  tools: [list_projects_default, get_project_default, list_blog_posts_default, get_blog_post_default, list_achievements_default, list_social_posts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
